# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0b875972054dc5970c4354791c584840d4910e6eb0c73cd476cb24f149b85cb11829762795418fb1ec697877b2aee390d2d59367037a465ed56a3a690a9335

test:
  secret_key_base: 6f616f1753bdaf5ac51ec076ef7c87071288184c7372b8167ce0d9c038a674385694e66c641f92994324e66539801f6b717cd8a484321ba5a1b18806c62a7f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
